### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by Gabsii** [Gabsii/spoti-vote#119]
We should design a new logo, the old one looks strange..

**Comment by Vinetos** [comment]
What is the current logo ?

**Comment by Gabsii** [comment]
@Vinetos @Michiocre @carohauta

**GUIDELINES:**

- Must contain the letter S
- Can't look too much like the current Spotify logo (because of their branding guidelines)
- variation in the 4 main colours would be cool but not necessary
   - red #E74C3C
   - green #2ECC71 or #1DB954 (whatever fits better) 
   - blue #3498DB
   - yellow #F1C40F
- preferably in a round shape
- should fit the main theme of [spoti-vote.com](https://spoti-vote.com)

I'm looking forward to your submissions 😄

**Comment by Michiocre** [comment]
![image](https://user-images.githubusercontent.com/7807995/66408036-7d964880-e9ee-11e9-9f88-19585cb99fb1.png)

 #123 For all Versions
