### ISSUE TITLE
Explore a better backend structure

### ISSUE THREAD

**Issue by Michiocre** [Gabsii/spoti-vote#128]
Try implementing rooms and namespaces as provided by socket.io. This might simplify some of the backend processes.
[socket.io/rooms](https://socket.io/docs/rooms-and-namespaces)

#127 New feature branch

**Comment by Gabsii** [comment]
Great idea! 
Might also be worth checking if socket.io supports some serverless features so the deployment process gets simplified.

**Comment by Michiocre** [comment]
#181 Removed Sockets completely so no more need.
