### ISSUE TITLE
Frontend Formatting Problems

### ISSUE THREAD

**Issue by Hamomor** [Gabsii/spoti-vote#129]
1.) Although the Site is  on Desktop Fullscreen the footer seems to be crammed in the middle
![image](https://user-images.githubusercontent.com/56870969/67276814-bdb4fb00-f4c5-11e9-9b65-ad39134050ee.png)

2.) On the policies site chapter 1 paragraph 2 the url formtting seems to be bad ("/\/\"). If this style is intentional, there are 2 times with normal "//".
![image](https://user-images.githubusercontent.com/56870969/67277089-551a4e00-f4c6-11e9-9aff-ba772b325a4c.png)

3.) On the policies site the link formatting is without a space between prior word and link e.g.
![image](https://user-images.githubusercontent.com/56870969/67277271-c35f1080-f4c6-11e9-9e5c-5ae9eaa8c5eb.png)

4.) On the policies site the footer is  just a white block. Seems like an very sudden end.
![image](https://user-images.githubusercontent.com/56870969/67277301-cf4ad280-f4c6-11e9-8e58-0813bdd1f42e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome

AND

**Smartphone (please complete the following information):**
 - Device: OnePlus2
 - Browser Chrome

**Comment by Gabsii** [comment]
Hey @Hamomor 

Feel free to open PRs to said topics since they don't require huge prior knowledge about our codebase and are relatively small issues to fix. 
Looking forward to review your PR! 😄 

Greetings,
Gabsii

**Comment by drigio** [comment]
Hey @Gabsii I would like to work on this if possible.

**Comment by drigio** [comment]
@sanketd617 Next time read comments before you send a pr! Others are working on it too!
