### ISSUE TITLE
Spotify Premium Subscription with Student Program

### ISSUE THREAD

**Issue by Hamomor** [Gabsii/spoti-vote#131]
Wenn connected Spotify Account has student subscription, hosting a room is not possible. Error Message:
![image](https://user-images.githubusercontent.com/56870969/67432027-c69cee00-f5e5-11e9-8b57-8f19499bf4db.png)

Was functioning before entering student program and is now on mobile as well as desktop version

**Comment by Gabsii** [comment]
@Michiocre is there a 3rd, currently unchecked option for premium users with the student discount? Please check if student discount premium users are different and if they have the possibility to access the player api endpoint. Thanks in advance

**Comment by Gabsii** [comment]
@Michiocre can you check if there is a possibility that the response varies in the way it is written? Uppercase, lowercase, CAPS LOCK, etc. ?

**Comment by Gabsii** [comment]
this issue will be resolved in #227 if I am correct
