### ISSUE TITLE
clicking Join does not work on iphone safari/chrome

### ISSUE THREAD

**Issue by phishy** [Gabsii/spoti-vote#170]
**Describe the bug**
When I visit 192.168.0.12:8080, type in a room code, and press Join, nothing happens.

**To Reproduce**
See above

**Expected behavior**
Should redirect to Room

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 13.2
 - Browser: Safari & Chrome
 - Version

**Additional context**

**Comment by Gabsii** [comment]
Hello @phishy, 

Could you check your console (F12 or Cmd Shift J >Console ) for any error messages? If yes, please post them here 😄

**Comment by Gabsii** [comment]
will close this due to inactivitiy. feel free to reopen
