### ISSUE TITLE
How Can This Be Resolved?

### ISSUE THREAD

**Issue by daledali** [Gabsii/spoti-vote#223]
Logs from https://vercel.com/

18:19:26.550  	Cloning github.com/daledali/spoti-vote (Branch: master, Commit: 1219d5b)
18:19:27.362  	Cloning completed in 812ms
18:19:27.366  	Analyzing source code...
18:19:27.366  	Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
18:19:29.835  	Installing build runtime...
18:19:30.316  	Build runtime installed: 480.630ms
18:19:31.256  	Installing dependencies...
18:19:31.470  	yarn install v1.22.4
18:19:31.505  	info No lockfile found.
18:19:31.515  	[1/4] Resolving packages...
18:19:31.527  	Installing build runtime...
18:19:31.934  	Build runtime installed: 407.323ms
18:19:32.288  	warning babel-core > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
18:19:32.288  	warning babel-core > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
18:19:32.772  	Installing dependencies...
18:19:33.124  	warning babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
18:19:33.133  	warning babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
18:19:35.551  	warning glamor > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
18:19:35.976  	warning jest > jest-cli > jest-config > babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
18:19:36.242  	warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
18:19:36.256  	warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
18:19:36.259  	warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
18:19:36.335  	warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
18:19:36.473  	warning jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
18:19:36.473  	warning jest-environment-jsdom-fourteen > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
18:19:36.804  	warning nodemon > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
18:19:36.806  	warning nodemon > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
18:19:38.491  	warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
18:19:38.565  	warning resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
18:19:38.907  	warning sw-precache-webpack-plugin > sw-precache@5.2.1: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
18:19:38.938  	warning sw-precache-webpack-plugin > sw-precache > sw-toolbox@3.6.0: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
18:19:39.475  	warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
18:19:39.701  	warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
18:19:40.000  	warning workbox-webpack-plugin > workbox-build > @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
18:19:40.056  	warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
18:19:40.058  	warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
18:19:40.058  	warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
18:19:40.058  	warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
18:19:40.059  	warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
18:19:40.219  	[2/4] Fetching packages...
18:19:54.403  	info fsevents@2.1.3: The platform "linux" is incompatible with this module.
18:19:54.403  	info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
18:19:54.412  	info fsevents@1.2.13: The platform "linux" is incompatible with this module.
18:19:54.412  	info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
18:19:54.419  	[3/4] Linking dependencies...
18:19:54.422  	warning " > babel-jest@26.3.0" has unmet peer dependency "@babel/core@^7.0.0".
18:19:54.422  	warning "babel-jest > babel-preset-jest@26.3.0" has unmet peer dependency "@babel/core@^7.0.0".
18:19:54.422  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@0.1.3" has unmet peer dependency "@babel/core@^7.0.0".
18:19:54.422  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
18:19:54.422  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
18:19:54.422  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
18:19:54.422  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
18:19:54.423  	warning " > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
18:19:54.423  	warning " > babel-plugin-named-asset-import@0.3.6" has unmet peer dependency "@babel/core@^7.1.0".
18:19:54.426  	warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "@typescript-eslint/eslint-plugin@2.x".
18:19:54.427  	warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "@typescript-eslint/parser@2.x".
18:19:54.432  	warning " > react-text-marquee@1.0.1" has incorrect peer dependency "react@^15.0.1".
18:20:02.906  	[4/4] Building fresh packages...
18:20:04.310  	success Saved lockfile.
18:20:04.317  	Done in 32.85s.
18:20:04.530  	yarn install v1.22.4
18:20:04.579  	info No lockfile found.
18:20:04.592  	[1/4] Resolving packages...
18:20:07.900  	Uploading build outputs...
18:20:11.388  	[2/4] Fetching packages...
18:20:11.539  	info fsevents@2.1.3: The platform "linux" is incompatible with this module.
18:20:11.539  	info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
18:20:11.547  	info fsevents@1.2.13: The platform "linux" is incompatible with this module.
18:20:11.547  	info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
18:20:11.553  	[3/4] Linking dependencies...
18:20:11.555  	warning " > babel-jest@26.3.0" has unmet peer dependency "@babel/core@^7.0.0".
18:20:11.555  	warning "babel-jest > babel-preset-jest@26.3.0" has unmet peer dependency "@babel/core@^7.0.0".
18:20:11.555  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@0.1.3" has unmet peer dependency "@babel/core@^7.0.0".
18:20:11.555  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
18:20:11.555  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
18:20:11.555  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
18:20:11.555  	warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
18:20:11.556  	warning " > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
18:20:11.556  	warning " > babel-plugin-named-asset-import@0.3.6" has unmet peer dependency "@babel/core@^7.1.0".
18:20:11.559  	warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "@typescript-eslint/eslint-plugin@2.x".
18:20:11.559  	warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "@typescript-eslint/parser@2.x".
18:20:11.561  	warning " > react-text-marquee@1.0.1" has incorrect peer dependency "react@^15.0.1".
18:20:19.379  	[4/4] Building fresh packages...
18:20:20.581  	success Saved lockfile.
18:20:20.587  	Done in 16.06s.
18:20:20.610  	Running "yarn run build"
18:20:20.773  	yarn run v1.22.4
18:20:20.813  	$ node frontend/scripts/build.js
18:20:21.584  	Creating an optimized production build...
18:20:36.506  	Compiled with warnings.
18:20:36.506  	./frontend/src/serviceWorker.js
18:20:36.506  	  Line 44:21:   Unexpected console statement  no-console
18:20:36.506  	  Line 72:29:   Unexpected console statement  no-console
18:20:36.506  	  Line 85:29:   Unexpected console statement  no-console
18:20:36.506  	  Line 123:13:  Unexpected console statement  no-console
18:20:36.506  	Search for the keywords to learn more about each warning.
18:20:36.506  	To ignore, add // eslint-disable-next-line to the line before.
18:20:36.506  	File sizes after gzip:
18:20:36.533  	  79.98 KB  build/static/js/3.5d024541.chunk.js
18:20:36.533  	  31.22 KB  build/static/js/4.5739efe6.chunk.js
18:20:36.533  	  17.23 KB  build/static/js/0.90d9ffa1.chunk.js
18:20:36.533  	  6.66 KB   build/static/js/7.55d66b37.chunk.js
18:20:36.533  	  5.87 KB   build/static/js/main.e2884c1a.chunk.js
18:20:36.533  	  5.28 KB   build/static/js/11.323aa540.chunk.js
18:20:36.534  	  4.12 KB   build/static/js/6.620b4d0a.chunk.js
18:20:36.534  	  3.29 KB   build/static/js/9.2a0e3382.chunk.js
18:20:36.534  	  2.6 KB    build/static/js/5.fe653fcb.chunk.js
18:20:36.534  	  1.86 KB   build/static/js/8.b89e34aa.chunk.js
18:20:36.534  	  1.58 KB   build/static/js/runtime~main.87ab6503.js
18:20:36.534  	  1.41 KB   build/static/css/main.cad3e6eb.chunk.css
18:20:36.534  	  1.29 KB   build/static/js/10.56606e18.chunk.js
18:20:36.534  	  415 B     build/static/css/7.94e111de.chunk.css
18:20:36.534  	The project was built assuming it is hosted at https://spoti-vote.com.
18:20:36.534  	You can control this with the homepage field in your package.json.
18:20:36.534  	The frontend/build folder is ready to be deployed.
18:20:36.534  	You may serve it with a static server:
18:20:36.534  	  yarn global add serve
18:20:36.534  	  serve -s frontend/build
18:20:36.534  	Find out more about deployment here:
18:20:36.534  	  bit.ly/CRA-deploy
18:20:36.564  	Done in 15.79s.
18:20:36.801  	Uploading build outputs...
18:20:44.306  	Build completed. Populating build cache...

**Comment by daledali** [comment]
18:39:24.961  	Cloning github.com/daledali/spoti-vote (Branch: master, Commit: 20f3abf)
18:39:25.980  	Cloning completed in 1019ms
18:39:25.982  	Analyzing source code...
18:39:25.983  	Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
18:39:27.110  	Installing build runtime...
18:39:27.584  	Build runtime installed: 473.665ms
18:39:28.075  	Installing build runtime...
18:39:28.565  	Build runtime installed: 490.122ms
18:39:28.645  	SyntaxError: Unexpected token h in JSON at position 1074
18:39:28.645  	    at JSON.parse (<anonymous>)
18:39:28.645  	    at scanParentDirs (/vercel/23674800ec1c0cce/.build-utils/node_modules/@vercel/build-utils/dist/index.js:31694:36)
18:39:28.645  	    at async getNodeVersion (/vercel/23674800ec1c0cce/.build-utils/node_modules/@vercel/build-utils/dist/index.js:31672:29)
18:39:28.645  	    at async downloadInstallAndBundle (/vercel/23674800ec1c0cce/.build-utils/.builder/node_modules/@now/node/dist/index.js:28304:25)
18:39:28.645  	    at async Object.build (/vercel/23674800ec1c0cce/.build-utils/.builder/node_modules/@now/node/dist/index.js:28487:78)
18:39:28.645  	    at async buildStep (/var/task/sandbox-worker.js:21362:20)
18:39:28.645  	    at async mainSub (/var/task/sandbox-worker.js:21096:9)
18:39:28.645  	    at async main (/var/task/sandbox-worker.js:20959:5)
18:39:29.338  	SyntaxError: Unexpected token h in JSON at position 1074
18:39:29.338  	    at JSON.parse (<anonymous>)
18:39:29.339  	    at getPkg (/vercel/b858f4748364150c/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:2498:22)
18:39:29.339  	    at Object.build (/vercel/b858f4748364150c/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:2539:17)
18:39:29.339  	    at async buildStep (/var/task/sandbox-worker.js:21362:20)
18:39:29.339  	    at async mainSub (/var/task/sandbox-worker.js:21096:9)
18:39:29.339  	    at async main (/var/task/sandbox-worker.js:20959:5)
18:39:30.706  	Done with "backend/server.js"
18:39:31.031  	Done with "package.json"

**Comment by Gabsii** [comment]
Hello @daledali 

Can you provide more information? 
The current version of spoti-vote.com is running on different domains and does not yet work with a Vercel deployment. The deployment on Vercel is only for the frontend part whereas all the backend lives under a different domain. 
If you want to implement the necessary vercel configuration needed feel free to open a PR! 😄 

Best wishes

**Comment by daledali** [comment]
PR?

**Comment by Gabsii** [comment]
@daledali PR means Pull Request 😅
