### ISSUE TITLE
Explore better error logging services

### ISSUE THREAD

**Issue by Gabsii** [Gabsii/spoti-vote#233]
**Is your feature request related to a problem? Please describe.**
currently, a lot of lines are prepended `// eslint-disable-next-line no-console` which is against our linting rules. It would be best if we could do something about this. 

**Describe the solution you'd like**
Either we write a wrapper for `console.log` or we search for services that do the logging for you (e.g. [TrackJS](https://trackjs.com/))

**Additional context**
I came across it in #227

**Comment by aFINKndreas** [comment]
would use sentry for error logging (also good pricing, and could selfhost open-source version)

**Comment by aFINKndreas** [comment]
and just use winston and winston-transport-browserconsole to setup the same logger for client and server side.

**Comment by Michiocre** [comment]
For now this should do fine: #240
