### ISSUE TITLE
Upgrade React Class Components to Functional Components

### ISSUE THREAD

**Issue by Gabsii** [Gabsii/spoti-vote#234]
Sooner or later class components will lose support. To no become a security issue and stay within the support this should be resolved

**Comment by Michiocre** [comment]
> I see that host is being passed around a lot, maybe we put the host into a context provider? If you think so too please mention it in issue #234 as a reminder for me

**Comment by Michiocre** [comment]
^in frontend/src/pages/dashboard line 115

**Comment by Mikaceniuk** [comment]
Hello, can i help upgrading?

**Comment by Michiocre** [comment]
> There also is a much better way to get the roomId (window.location.pathname.split('/')[2] is the roomID I assume). It leverages react hooks (new React API), I will look into migrating our components from class-based components to functional components once this PR is merged.
Issue #234 will be used for further discussion

**Comment by saifulshihab** [comment]
Hey, Can I contribute?

**Comment by aFINKndreas** [comment]
WIP can be seen here: https://github.com/Gabsii/spoti-vote/pull/241
