### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by Michiocre** [Gabsii/spoti-vote#3]
The login Button doesnt seem to work.

**Comment by Gabsii** [comment]
Dear @Michiocre !

We are aware of the issue and currently working to resolve it. 
Please be patient and wait for the next update. 

Sincerely, 
Gabsii

**Comment by Gabsii** [comment]
This issue was fixed with the latest [commit](https://github.com/Gabsii/spoti-vote/commit/66b147be67913bce29d1fda6108f96a8b3bfa29c).
