### ISSUE TITLE
Voting System is broken

### ISSUE THREAD

**Issue by Gabsii** [Gabsii/spoti-vote#34]
**Describe your problem.**

When logging into a room the app only takes all the votes and sets a new song as soon as the old song ran for the n-th time. So the voting system recognises the votes too late or the the spotify api request is sent too late. 

**Can it be reprodueced?**

Open spotify, create a room, start a song, vote, skip to the end. 
--> Recognise that the started song plays again

**Where did the error occur?**

Most likely server sided (no exact error message thrown)

**Comment by Michiocre** [comment]
Since i cant seem to recreate this error, i will examine your server myself later this day

**Comment by Michiocre** [comment]
The only similar error i noticed is when the song is not on spotify, but then it just doesnt start

**Comment by Michiocre** [comment]
I have found the error, this happens when the user hosts multiple rooms, to fix this i either have to reimplement an instante room deletion or we have to make sure one user can only host one room.

**Comment by Michiocre** [comment]
This problem has been resolved

**Comment by Gabsii** [comment]
Was option 1 or 2 used?
