### ISSUE TITLE
Login Page - UI Update #1

### ISSUE THREAD

**Issue by Michiocre** [Gabsii/spoti-vote#7]
De isch ned gut

**Comment by Gabsii** [comment]
Got to find someone who creates the content of the page.

**Comment by Gabsii** [comment]
Login page is currently on hold and was set to the most basic needs only (create room and connect to room) this is going to change as soon as I figure out what I need on the Login Page.

**Comment by Gabsii** [comment]
From now on the new Login Page Design will be implemented. I'll keep you up-to-date!
