### ISSUE TITLE
Cant log out of spotify

### ISSUE THREAD

**Issue by Michiocre** [Gabsii/spoti-vote#75]
**Describe your problem.**

After linking an spotify account you cant unlink your account and connect with a different one

**Can it be reproduced?**

Ye

**Where did the error occur?**

Frontpage

**Comment by Gabsii** [comment]
Will implement a basic dashboard that can be accessed if the user has a Spotify Token in his cookies. Logouts will destroy the cookie. Any idea what to put on the dashboard?

**Comment by Gabsii** [comment]
Closing issue due to the implementation of a dashboard.

**Comment by Michiocre** [comment]
It does not seem as thou the logout button works correctly.
Also why does this popup look different to all the others.
